### ISSUE TITLE
[Feature] Please support theme setting?

### ISSUE THREAD

**Issue by code-lixm** [xmindltd/xmind-generator#28]
I want to use this library to build xmind files, but now I need to do a simple theme setup, is there a quick way to implement it? I tried to add the theme field to content.json, but looking like dataStructureVersion:2 would cause the data currently parsed by xmind to fail to open.

If you have time, please give me an answer, thks

**Comment by code-lixm** [comment]
I found a solution

**Comment by code-lixm** [comment]
I found a solution

**Comment by satzynu** [comment]
Can you please share the details of the solution ?

**Comment by nevahid** [comment]
Hi @code-lixm, what is your solution? How did you handle theme problem?
